version: "3"
services:
  web:
    image: grimnir777/maestro-back:1.0.1
    env_file: 
      - ./.env
    ports:
    - "3000:3000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27019:27019"
