apiVersion: v1
kind: Service
metadata:
  labels:
    app: maestro-back
  name: backend-service
  namespace: thibaudg
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: maestro-back
