apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: maestro-app
  name: minio-pvc
  namespace: thibaudg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: "csi-cinder-classic"
